### ISSUE TITLE
Add unit tests and coverage tracker

### ISSUE THREAD

**Issue by Nircek** [Nircek/resistorer#9]
Add unit tests and some software (Travis CI?) to automatically run them. Also, it will be good to have some software that tracks the coverage of the code.
- [x] coverage soft
- [x] add some tests
- [x] automatically run them
- [x] add more tests
- [ ] even more tests
- [ ] make sure there are a lot of colourful badges in README
